### ISSUE TITLE
패키지 구조 변경에 대한 고민

### ISSUE THREAD

**Issue by binam33** [oscka/starter#1]
현재와 같이 "레이어 > 업무" 순이 아니라
예) com.hanex.starter.controller.customer
업무를 먼저 묶고 레이어를 입력하는 순서로 설정해야 함
예) com.hanex.starter.customer.controller
그래야 cqrs도 적용 가능할 듯 함 
예) com.hanex.starter.customer.command(query).controller(domain)
처럼 가는 게 어떨까 고민중입니다.(auth는 이미 그렇게 되어있네요.)

더 좋은 의견이나 방안이 있으면 공유 부탁드립니다.

**Comment by evelyn0410** [comment]
exception  은 common 패키지에 넣은후, 업무 > 레이어 순서로 변경하겠습니다.

방안 (1) 
com.hanex.starter
│
├── common
│   ├── exception 
│   ├── config
│   ├── properties
│   └── util
├── customer
│   ├── model
│   ├── controller
│   ├── service
│   └── domain 
└── 


방안 (2) 
[cqrs 참고]
https://osc-korea.atlassian.net/wiki/spaces/TECH/pages/33259521/11.4+CQRS

com.hanex.starter
│
├── common
│   ├── exception 
│   ├── config
│   ├── properties
│   └── util
├── customer
│   ├── command
│   │   ├── events
│   │   ├── controller
│   │   ├── service
│   │   └── domain 
│   ├── query
│   │   ├── model
│   │   ├── controller
│   │   ├── service
│   │   └── domain 
└── 

방안(1) 처럼 업무 > 레이어로 나누는 방법
방안(2) 처럼 업무 > command 레이어 , query 레이어로 나누는 방법

둘중 어떻게 수정해야할까요?

**Comment by binam33** [comment]
방안(2)가 맞을 것 같습니다.
